language: c

before_install:
  - sudo add-apt-repository ppa:directhex/monoxide -y
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq mono-devel > /dev/null
  - mono --version
  - mozroots --import --sync

script:
  - wget http://nuget.org/nuget.exe
  - mono --runtime=v4.0 nuget.exe restore
  - xbuild /property:Configuration=Release
  - mono --runtime=v4.0 packages/NUnit.Runners.2.6.2/tools/nunit-console.exe -noxml -nodots -labels -stoponerror Criteo.Memcache.UTest/bin/Release/Criteo.Memcache.UTest.dll
